### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by sims1253** [coala/coala-html#103]
log:
```
pip install coala-html
Collecting coala-html
  Downloading coala_html-0.3-py3-none-any.whl
Requirement already satisfied: coala~=0.9 in /home/m0hawk/Documents/dev/coala-analyzer/venv/lib/python3.6/site-packages (from coala-html)
Requirement already satisfied: requests~=2.12 in /home/m0hawk/Documents/dev/coala-analyzer/venv/lib/python3.6/site-packages (from coala~=0.9->coala-html)
Requirement already satisfied: Pygments~=2.1 in /home/m0hawk/Documents/dev/coala-analyzer/venv/lib/python3.6/site-packages (from coala~=0.9->coala-html)
Requirement already satisfied: dependency-management~=0.3.1 in /home/m0hawk/Documents/dev/coala-analyzer/venv/lib/python3.6/site-packages (from coala~=0.9->coala-html)
Requirement already satisfied: appdirs~=1.4 in /home/m0hawk/Documents/dev/coala-analyzer/venv/lib/python3.6/site-packages (from coala~=0.9->coala-html)
Requirement already satisfied: libclang-py3~=3.4.0 in /home/m0hawk/Documents/dev/coala-analyzer/venv/lib/python3.6/site-packages (from coala~=0.9->coala-html)
Requirement already satisfied: PyPrint~=0.2.6 in /home/m0hawk/Documents/dev/coala-analyzer/venv/lib/python3.6/site-packages (from coala~=0.9->coala-html)
Requirement already satisfied: colorlog~=2.7 in /home/m0hawk/Documents/dev/coala-analyzer/venv/lib/python3.6/site-packages (from coala~=0.9->coala-html)
Requirement already satisfied: coala-utils~=0.6.0 in /home/m0hawk/Documents/dev/coala-analyzer/venv/lib/python3.6/site-packages (from coala~=0.9->coala-html)
Requirement already satisfied: sarge~=0.1.4 in /home/m0hawk/Documents/dev/coala-analyzer/venv/lib/python3.6/site-packages (from dependency-management~=0.3.1->coala~=0.9->coala-html)
Requirement already satisfied: termcolor~=1.1.0 in /home/m0hawk/Documents/dev/coala-analyzer/venv/lib/python3.6/site-packages (from PyPrint~=0.2.6->coala~=0.9->coala-html)
Requirement already satisfied: colorama~=0.3.7 in /home/m0hawk/Documents/dev/coala-analyzer/venv/lib/python3.6/site-packages (from PyPrint~=0.2.6->coala~=0.9->coala-html)
Installing collected packages: coala-html
Successfully installed coala-html-0.3
m0hawk@antergos-book ..ents/dev/coala-analyzer/coala_showcase (git)-[master] % coala-html
Traceback (most recent call last):
  File "/home/m0hawk/Documents/dev/coala-analyzer/venv/bin/coala-html", line 7, in <module>
    from coalahtml.coala_html import main
  File "/home/m0hawk/Documents/dev/coala-analyzer/venv/lib/python3.6/site-packages/coalahtml/coala_html.py", line 24, in <module>
    from coalahtml.helper import (
  File "/home/m0hawk/Documents/dev/coala-analyzer/venv/lib/python3.6/site-packages/coalahtml/helper.py", line 6, in <module>
    from coalahtml import Constants
  File "/home/m0hawk/Documents/dev/coala-analyzer/venv/lib/python3.6/site-packages/coalahtml/Constants.py", line 12, in <module>
    LOCALHOST = socket.gethostbyname(socket.gethostname())
socket.gaierror: [Errno -2] Name or service not known

```

**Comment by sils** [comment]
gets fixed by https://github.com/coala/coala-html/pull/104
